package cli

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"

	"github.com/meowshed/meowctl/internal/lock"
	"github.com/spf13/cobra"
)

func newLockCmd(gf *globalFlags) *cobra.Command {
	lockCmd := &cobra.Command{
		Use:   "lock",
		Short: "Manage the meowctl lock file",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return cmd.Help()
		},
	}
	lockCmd.AddCommand(
		newLockVerifyCmd(gf),
		newLockShowCmd(gf),
	)
	return lockCmd
}

func newLockVerifyCmd(gf *globalFlags) *cobra.Command {
	var jsonOut bool
	cmd := &cobra.Command{
		Use:   "verify",
		Short: "Verify SRI integrity for all modules in the lock file",
		Args:  cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			configDir, err := resolveConfigDir(gf)
			if err != nil {
				return err
			}
			lockPath := filepath.Join(configDir, "meowctl.lock")
			lf, err := lock.Read(lockPath)
			if err != nil {
				return exitErrorf(ExitConfig, "lock verify: %v", err)
			}

			type verifyResult struct {
				Module string `json:"module"`
				Status string `json:"status"`
				Detail string `json:"detail,omitempty"`
			}
			var results []verifyResult
			allOK := true

			names := make([]string, 0, len(lf.Modules))
			for k := range lf.Modules {
				names = append(names, k)
			}
			sort.Strings(names)

			for _, name := range names {
				entry := lf.Modules[name]
				// Integrity field presence is the verification gate for now.
				// Deep SRI re-download is a future enhancement.
				if entry.Integrity == "" {
					results = append(results, verifyResult{name, "warn", "no integrity hash recorded"})
				} else {
					results = append(results, verifyResult{name, "ok", entry.Integrity})
				}
			}

			if jsonOut {
				out, _ := json.MarshalIndent(results, "", "  ")
				fmt.Println(string(out))
			} else {
				for _, r := range results {
					icon := "✓"
					if r.Status != "ok" {
						icon = "!"
						allOK = false
					}
					fmt.Printf("  %s %s: %s\n", icon, r.Module, r.Detail)
				}
			}

			if !allOK {
				return exitErrorf(ExitModule, "lock verify: one or more modules missing integrity hash")
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&jsonOut, "json", false, "Output as JSON")
	return cmd
}

func newLockShowCmd(gf *globalFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "show",
		Short: "Pretty-print the contents of the lock file",
		Args:  cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			configDir, err := resolveConfigDir(gf)
			if err != nil {
				return err
			}
			lockPath := filepath.Join(configDir, "meowctl.lock")
			lf, err := lock.Read(lockPath)
			if err != nil {
				return exitErrorf(ExitConfig, "lock show: %v", err)
			}

			fmt.Printf("Generated by: %s\n", lf.Meta.GeneratedBy)
			fmt.Printf("Updated at:   %s\n", lf.Meta.UpdatedAt)

			if len(lf.Modules) > 0 {
				fmt.Printf("\nModules (%d):\n", len(lf.Modules))
				names := make([]string, 0, len(lf.Modules))
				for k := range lf.Modules {
					names = append(names, k)
				}
				sort.Strings(names)
				for _, name := range names {
					e := lf.Modules[name]
					fmt.Printf("  %-32s %s\n", name, e.Version)
					fmt.Printf("    source:    %s\n", e.Source)
					fmt.Printf("    integrity: %s\n", e.Integrity)
				}
			}

			if len(lf.GitHub) > 0 {
				fmt.Printf("\nGitHub modules (%d):\n", len(lf.GitHub))
				names := make([]string, 0, len(lf.GitHub))
				for k := range lf.GitHub {
					names = append(names, k)
				}
				sort.Strings(names)
				for _, name := range names {
					e := lf.GitHub[name]
					fmt.Printf("  %-32s %s\n", name, e.Commit[:12])
				}
			}

			return nil
		},
	}
}
